#!/bin/sh
#
# Xcode Cloud post-clone hook for the Breeze mobile app.
#
# WHY THIS EXISTS
# ---------------
# `apps/mobile/ios` is generated by `expo prebuild`, not committed (Continuous
# Native Generation — see apps/mobile/.gitignore). A fresh Xcode Cloud clone
# therefore contains no `BreezeRMM.xcworkspace`, and the build fails before it
# starts with:
#
#     Workspace BreezeRMM.xcworkspace does not exist at
#     apps/mobile/ios/BreezeRMM.xcworkspace
#
# Xcode Cloud runs this script immediately after cloning and before resolving
# the workspace, so this is the hook that has to produce the native project.
#
# WHY IT LIVES HERE
# -----------------
# Xcode Cloud looks for `ci_scripts` as a sibling of the .xcworkspace, which
# puts it inside the ignored `ios/` directory. `.gitignore` re-includes exactly
# this one subdirectory; everything else under `ios/` stays generated.
#
# WHY IT RE-EXECS ITSELF
# ----------------------
# `expo prebuild` replaces the whole `ios/` directory — including `ci_scripts`,
# and including this file — even without `--clean`. `sh` reads a script
# incrementally rather than loading it whole, so letting the file vanish
# mid-execution is undefined behaviour. Verified locally: prebuild deletes
# `ios/ci_scripts` outright. So the first thing this does is copy itself
# somewhere prebuild cannot reach and hand over to that copy.
#
# `sh`, not `bash`, and no `pipefail`: Xcode Cloud executes these with /bin/sh.

set -eu

# ---------------------------------------------------------------------------
# Resolve the checkout root BEFORE any re-exec, while $0 is still the real path.
# CI_PRIMARY_REPOSITORY_PATH is Xcode Cloud's checkout root; CI_WORKSPACE is the
# older name. The fallback walks up from ios/ci_scripts -> ios -> mobile ->
# apps -> repo root.
# ---------------------------------------------------------------------------
if [ -z "${BREEZE_CI_REPO_ROOT:-}" ]; then
  BREEZE_CI_REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-${CI_WORKSPACE:-}}"
  if [ -z "$BREEZE_CI_REPO_ROOT" ]; then
    BREEZE_CI_REPO_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
  fi
  export BREEZE_CI_REPO_ROOT
fi

# Hand over to a copy outside ios/, once.
if [ "${BREEZE_CI_REEXEC:-}" != "1" ]; then
  SELF_COPY="$(mktemp -t breeze_ci_post_clone)"
  cat "$0" > "$SELF_COPY"
  BREEZE_CI_REEXEC=1
  export BREEZE_CI_REEXEC
  echo "--- ci_post_clone: re-exec from $SELF_COPY (prebuild deletes this script's directory)"
  exec sh "$SELF_COPY"
fi

REPO_ROOT="$BREEZE_CI_REPO_ROOT"
cd "$REPO_ROOT"
echo "--- ci_post_clone: generating the native iOS project"
echo "--- repo root: $REPO_ROOT"

# ---------------------------------------------------------------------------
# Toolchain. The Xcode Cloud image ships neither Node nor (reliably) CocoaPods,
# but does ship Homebrew.
# ---------------------------------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
  echo "--- installing Node"
  brew install node@22
  # Keg-only formula: not linked into PATH automatically.
  PATH="$(brew --prefix node@22)/bin:$PATH"
  export PATH
fi
echo "--- node $(node --version)"

# pnpm at the exact version pinned by the root package.json packageManager field.
corepack enable
corepack prepare --activate
echo "--- pnpm $(pnpm --version)"

if ! command -v pod >/dev/null 2>&1; then
  echo "--- installing CocoaPods"
  brew install cocoapods
fi

# Only the mobile package and its workspace dependencies. The API and web apps
# are irrelevant here and pulling them in roughly triples install time.
echo "--- installing JS dependencies"
pnpm install --filter breeze-mobile... --frozen-lockfile

# ---------------------------------------------------------------------------
# Build variables. Two of these gate a RELEASE build and make app.config.js
# throw when unset (src/config/sentryDsn.js, src/config/apiUrl.js). Xcode build
# phases do not inherit this script's environment, so whatever the Xcode Cloud
# workflow sets has to be written to the .env file the config phase reads.
#
# Nothing is invented: if the workflow sets none of them, no file is written and
# the build fails loudly at the config phase, which is the intended behaviour.
# Written via a temp file so an existing .env is never truncated to nothing.
# ---------------------------------------------------------------------------
ENV_FILE="$REPO_ROOT/apps/mobile/.env"
ENV_TMP="$ENV_FILE.ci_post_clone.tmp"
: > "$ENV_TMP"
for VAR in EXPO_PUBLIC_API_URL EXPO_PUBLIC_SENTRY_DSN EXPO_PUBLIC_POSTHOG_KEY \
           EXPO_PUBLIC_POSTHOG_HOST BREEZE_MOBILE_ALLOW_NO_SENTRY \
           BREEZE_MOBILE_ALLOW_PRIVATE_API_URL BREEZE_ASSOCIATED_DOMAINS; do
  eval "VALUE=\${$VAR:-}"
  if [ -n "$VALUE" ]; then
    echo "$VAR=$VALUE" >> "$ENV_TMP"
    # Deliberately not echoing values — the DSN is not a secret, but the
    # PostHog key and anything added here later may be.
    echo "--- .env: set $VAR"
  fi
done
if [ -s "$ENV_TMP" ]; then
  mv "$ENV_TMP" "$ENV_FILE"
else
  rm -f "$ENV_TMP"
  echo "--- .env: workflow set none of the build variables, leaving any existing file alone"
fi

# ---------------------------------------------------------------------------
# Symbolication. The DSN only makes events ARRIVE; making them READABLE needs
# source maps and dSYMs, which the @sentry/react-native/expo plugin uploads from
# two Xcode build phases using SENTRY_AUTH_TOKEN.
#
# Unlike the DSN this is a GENUINE SECRET, so it goes in its own gitignored file
# rather than .env — .env values are compiled into the JS bundle and would ship
# inside the IPA. Mark it "secret" in the Xcode Cloud workflow so it is redacted
# from build logs.
#
# Missing it does not fail the build, and that is exactly the hazard: events
# still arrive, but every JS frame is a minified bundle offset and native
# crashes have no symbols. It looks like working telemetry until someone needs
# to read a crash — the same "looks like it worked" class as shipping with no
# DSN at all. So warn loudly instead of passing over it in silence.
# ---------------------------------------------------------------------------
SENTRY_ENV_FILE="$REPO_ROOT/apps/mobile/.env.sentry-build-plugin"
if [ -n "${SENTRY_AUTH_TOKEN:-}" ]; then
  # Never echoed, only its presence.
  printf 'SENTRY_AUTH_TOKEN=%s\n' "$SENTRY_AUTH_TOKEN" > "$SENTRY_ENV_FILE"
  chmod 600 "$SENTRY_ENV_FILE"
  echo "--- .env.sentry-build-plugin: SENTRY_AUTH_TOKEN written"
elif [ -f "$SENTRY_ENV_FILE" ]; then
  echo "--- .env.sentry-build-plugin: workflow set no SENTRY_AUTH_TOKEN, leaving existing file alone"
else
  echo "--- WARNING: SENTRY_AUTH_TOKEN is not set. This build will report crashes" >&2
  echo "---          but WITHOUT source maps or dSYMs, so every JS frame will be a" >&2
  echo "---          minified bundle offset and native crashes will have no symbols." >&2
  echo "---          Set it as a secret environment variable on the Xcode Cloud" >&2
  echo "---          workflow (scopes: project:releases, org:read)." >&2
fi

# ---------------------------------------------------------------------------
# Generate ios/. Never `--clean`: it is even more destructive than the default,
# and the default already replaces this script's directory.
# ---------------------------------------------------------------------------
echo "--- expo prebuild"
cd "$REPO_ROOT/apps/mobile"
npx expo prebuild --platform ios --no-install

echo "--- pod install"
cd "$REPO_ROOT/apps/mobile/ios"
pod install

if [ ! -d "BreezeRMM.xcworkspace" ]; then
  echo "ci_post_clone: prebuild finished but BreezeRMM.xcworkspace is still missing" >&2
  exit 1
fi

# Put ci_scripts back so the tree matches what was cloned. Not needed for this
# build (Xcode Cloud already read the script), but it keeps a re-run of the
# same checkout working and makes the deletion non-surprising to anyone poking
# at the build machine.
if [ ! -d "$REPO_ROOT/apps/mobile/ios/ci_scripts" ]; then
  echo "--- restoring ci_scripts (prebuild removed it)"
  mkdir -p "$REPO_ROOT/apps/mobile/ios/ci_scripts"
  cp "$0" "$REPO_ROOT/apps/mobile/ios/ci_scripts/ci_post_clone.sh"
  chmod 755 "$REPO_ROOT/apps/mobile/ios/ci_scripts/ci_post_clone.sh"
fi

echo "--- ci_post_clone: done, workspace generated"
