/**
 * Canonical UUID (v1-v5) pattern, case-insensitive.
 *
 * Single shared definition for hot paths that must cheaply reject a non-UUID
 * identifier BEFORE touching the database (a non-UUID value in a uuid-typed
 * WHERE clause raises Postgres 22P02 through the caller). Used by the agent
 * WS handlers (routes/agentWs.ts) and the backup progress service — reuse
 * this for RFC-4122-strict validation rather than re-declaring a subtly
 * different regex. If all you need is "would this value raise 22P02?", with no
 * RFC-4122 requirement, use `PG_UUID_REGEX` below instead of writing a third
 * pattern.
 */
export const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * The canonical 8-4-4-4-12 hyphenated hex form, case-insensitive, with NO
 * version/variant constraint.
 *
 * Use this, not `UUID_REGEX`, when the only question is "will this value cast
 * cleanly instead of raising 22P02?". `UUID_REGEX` additionally requires an
 * RFC-4122 version (1-5) and variant (8/9/a/b) nibble, so it rejects ids that
 * Postgres stores happily — e.g. `33333333-3333-3333-3333-333333333333`, or any
 * id minted by a generator that does not set those bits. Guarding a lookup with
 * the stricter pattern would turn a real device into a 404.
 *
 * This is deliberately NARROWER than everything Postgres's uuid parser accepts:
 * Postgres also takes the hyphens omitted entirely, brace-wrapped forms, and
 * hyphens after any 4-digit group (see
 * https://www.postgresql.org/docs/current/datatype-uuid.html). Those forms are
 * rejected here, which is safe only because every id we match against is
 * generated by `defaultRandom()`/`gen_random_uuid()` and echoed back to clients
 * in canonical form — nothing first-party ever mints one of the alternates. If
 * that ever stops being true, normalize before testing rather than widening
 * this pattern.
 */
export const PG_UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
