// scripts/dev/test-stack/cli.ts
//
// Per-worktree ephemeral Postgres+Redis for the integration/RLS test suites
// (#3066). The historical shared containers on fixed ports (:5433/:6380) get
// clobbered when two worktree sessions run tests concurrently — per-test
// TRUNCATE ... CASCADE and role GRANTs interleave destructively, and one
// branch's migrations pollute the other's `breeze_migrations` ledger (the
// #3064 false bug report). This CLI gives each worktree its OWN stack:
//
//   pnpm test-stack up     # private containers, ephemeral ports, writes .env.test
//   pnpm vitest run -c vitest.integration.config.ts   # (from apps/api) as usual
//   pnpm test-stack down   # tears down containers AND the generated .env.test
//
// The generated worktree-local `.env.test` is how the suites find the stack —
// vitest.integration.config.ts and loadEnv.ts already read it; nothing about
// how tests are invoked changes. Without `test-stack up`, everything falls
// back to the shared :5433 defaults exactly as before (that's also the CI
// path — CI provisions its own isolated runner, so it never needs this).
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { deriveTestProjectName, envTestPath, stackEnv } from './project';
import { GENERATED_MARKER, isGeneratedEnvTest, renderEnvTest } from './envfile';

const ROOT = process.cwd();

function currentBranch(): string | undefined {
  try {
    const b = execFileSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'], { encoding: 'utf8' }).trim();
    return b === 'HEAD' ? undefined : b;
  } catch { return undefined; }
}

function composeArgs(project: string): string[] {
  return ['compose', '-p', project, '-f', 'docker-compose.test.yml'];
}

function docker(project: string, args: string[]): string {
  return execFileSync('docker', [...composeArgs(project), ...args], {
    cwd: ROOT,
    encoding: 'utf8',
    env: { ...process.env, ...stackEnv(project) },
    stdio: ['inherit', 'pipe', 'inherit'],
  });
}

function dockerInherit(project: string, args: string[]): void {
  execFileSync('docker', [...composeArgs(project), ...args], {
    cwd: ROOT,
    env: { ...process.env, ...stackEnv(project) },
    stdio: 'inherit',
  });
}

export function parsePublishedPort(output: string): number {
  const line = output.split('\n').map((l) => l.trim()).find(Boolean);
  const m = line?.match(/:(\d+)$/);
  if (!m) throw new Error(`Could not find a published port in compose output: ${JSON.stringify(output)} (no published port)`);
  return Number(m[1]);
}

function publishedPort(project: string, service: string, containerPort: number): number {
  return parsePublishedPort(docker(project, ['port', service, String(containerPort)]));
}

function refuseForeignEnvTest(force: boolean): void {
  const p = envTestPath(ROOT);
  if (!existsSync(p)) return;
  if (isGeneratedEnvTest(readFileSync(p, 'utf8')) || force) return;
  throw new Error(
    `${p} already exists and was not generated by test-stack — refusing to overwrite it.\n`
    + 'It probably points your test runs at the shared :5433 stack on purpose. '
    + 'Move it aside (or rerun with --force) if you want this worktree on a private stack.',
  );
}

function up(force: boolean): void {
  const project = deriveTestProjectName({ worktreePath: ROOT, branch: currentBranch() });
  refuseForeignEnvTest(force);
  console.log(`[test-stack] project=${project}`);
  dockerInherit(project, ['up', '-d', '--wait', '--wait-timeout', '120']);
  const pgPort = publishedPort(project, 'postgres-test', 5432);
  const redisPort = publishedPort(project, 'redis-test', 6379);
  writeFileSync(envTestPath(ROOT), renderEnvTest({ pgPort, redisPort, project }), 'utf8');
  console.log(JSON.stringify({
    project,
    pgPort,
    redisPort,
    databaseUrl: `postgresql://breeze_test:breeze_test@localhost:${pgPort}/breeze_test`,
    redisUrl: `redis://localhost:${redisPort}`,
    envTest: envTestPath(ROOT),
  }, null, 2));
}

function down(): void {
  const project = deriveTestProjectName({ worktreePath: ROOT, branch: currentBranch() });
  dockerInherit(project, ['down', '-v']);
  // Remove OUR .env.test so the next plain run falls back to the shared :5433
  // defaults instead of dialing dead ephemeral ports. Never touch a
  // hand-written one.
  const p = envTestPath(ROOT);
  if (existsSync(p) && isGeneratedEnvTest(readFileSync(p, 'utf8'))) unlinkSync(p);
}

function info(): void {
  const p = envTestPath(ROOT);
  if (!existsSync(p)) { console.log('No .env.test in this worktree — tests will use the shared :5433 defaults.'); return; }
  const content = readFileSync(p, 'utf8');
  console.log(isGeneratedEnvTest(content) ? content : `.env.test exists but was NOT generated by test-stack:\n${content}`);
}

function ls(): void {
  const out = execFileSync('docker', ['compose', 'ls', '--format', 'json'], { encoding: 'utf8' });
  const projects = (JSON.parse(out) as Array<{ Name: string; Status: string }>)
    .filter((pr) => pr.Name.startsWith('breeze-test-') || pr.Name === 'breeze');
  if (!projects.length) { console.log('No breeze test stacks running.'); return; }
  for (const pr of projects) console.log(`${pr.Name}\t${pr.Status}`);
}

function main(): void {
  const [cmd, ...rest] = process.argv.slice(2);
  switch (cmd) {
    case 'up': up(rest.includes('--force')); break;
    case 'down': down(); break;
    case 'info': info(); break;
    case 'ls': ls(); break;
    default:
      console.error('Usage: test-stack <up|down|info|ls> [--force]');
      console.error(`  up    start a private Postgres+Redis test stack for this worktree and write .env.test ("${GENERATED_MARKER.slice(2, 40)}...")`);
      console.error('  down  stop it, drop its volumes, and remove the generated .env.test');
      process.exit(1);
  }
}

main();
