// scripts/dev/test-stack/envfile.ts
//
// Renders the worktree-local `.env.test` that points the integration/RLS
// suites at THIS worktree's private test containers. The whole existing env
// chain already reads it (vitest.integration.config.ts and
// apps/api/src/__tests__/integration/loadEnv.ts both load the monorepo-root
// `.env.test`, and in a worktree "monorepo root" IS the worktree), so no test
// invocation changes at all — `pnpm vitest run -c vitest.integration.config.ts`
// just lands on the isolated instance.

/** First line of every file we generate — how we recognize our own output so
 *  we never clobber a hand-written .env.test. */
export const GENERATED_MARKER = '# generated by `pnpm test-stack` — safe to delete; regenerated on `test-stack up`';

export function isGeneratedEnvTest(content: string): boolean {
  return content.startsWith(GENERATED_MARKER);
}

export function renderEnvTest(opts: { pgPort: number; redisPort: number; project: string }): string {
  const { pgPort, redisPort, project } = opts;
  return [
    GENERATED_MARKER,
    `# compose project: ${project} (docker compose -p ${project} -f docker-compose.test.yml ...)`,
    '# These credentials match docker-compose.test.yml — local throwaway values, not secrets.',
    `DATABASE_URL=postgresql://breeze_test:breeze_test@localhost:${pgPort}/breeze_test`,
    `DATABASE_URL_APP=postgresql://breeze_app:breeze_test@localhost:${pgPort}/breeze_test`,
    'BREEZE_APP_DB_PASSWORD=breeze_test',
    'POSTGRES_PASSWORD=breeze_test',
    `REDIS_URL=redis://localhost:${redisPort}`,
    '',
  ].join('\n');
}
