package rebuild

import (
	"fmt"
	"strings"

	"github.com/breeze-rmm/agent/internal/backup/layout"
)

var supportedWindowsFilesystems = map[string]bool{"ntfs": true, "fat32": true, "vfat": true, "": true}

// windowsPartitionName returns the GPT partition name PlanPartitionsWindows
// writes for a partition of the given role. These are ROLE defaults, never
// the source layout.Partition.Name — the Windows collector stores
// \\.\PHYSICALDRIVEn#m device paths there (Ruling B7), which are not valid
// GPT partition names.
func windowsPartitionName(role string) string {
	switch role {
	case layout.RoleEFI:
		return "EFI system partition"
	case layout.RoleMSR:
		return "Microsoft reserved partition"
	case layout.RoleRecovery:
		return ""
	default:
		return "Basic data partition"
	}
}

// PlanPartitionsWindows is PlanPartitions' Windows twin (plan.go): same 1
// MiB alignment and end-of-disk reserve, but the partition that grows is
// always the recorded RoleRoot partition — Windows 11's default layout is
// ESP, MSR, C:, Recovery, so C: is rarely last (Review Focus 3), unlike
// PlanPartitions' "last root/data partition" rule. No filesystem-UUID
// validation: NTFS/FAT32 volume serials are regenerated by format.com, not
// carried forward like ext4/xfs/vfat's mkfs -U/-i are on Linux.
// manifestBytes is the whole-machine file manifest's total logical content
// size (winPreflight computes it before calling this, since hard links
// become copies under Windows restore — Global Constraint "Sizing").
// GPT attributes are copied verbatim from the source (Global Constraint
// "partition GUIDs and GPT attributes preserved") — the planner is not the
// place to add or clear bits. Task 11's winProvision ORs in the
// no-drive-letter bit at write time and Task 13 clears it.
func PlanPartitionsWindows(src *layout.Disk, targetSizeBytes int64, sectorSize int, manifestBytes int64) (*Plan, error) {
	if src == nil {
		return nil, &RefusalError{Reason: "no source disk in layout"}
	}
	if sectorSize <= 0 {
		sectorSize = 512
	}
	var parts []layout.Partition
	for _, p := range src.Partitions {
		if p.Kind == "" && p.Number > 0 {
			parts = append(parts, p)
		}
	}
	if len(parts) == 0 {
		return nil, &RefusalError{Reason: "source disk has no partitions"}
	}
	growIdx := -1
	for i, p := range parts {
		if p.Role == layout.RoleRoot {
			growIdx = i
			break
		}
	}
	if growIdx == -1 {
		return nil, &RefusalError{Reason: "source disk has no root (C:) partition"}
	}
	var fixed, growMin int64
	for i, p := range parts {
		fs := strings.ToLower(p.Filesystem)
		if !supportedWindowsFilesystems[fs] {
			return nil, &RefusalError{Reason: fmt.Sprintf("partition %d filesystem %q is not supported by the Windows engine (ntfs, fat32)", p.Number, p.Filesystem)}
		}
		if i == growIdx {
			need := p.UsedBytes
			if manifestBytes > need {
				need = manifestBytes
			}
			growMin = int64(float64(need) * 1.1)
			if growMin < GiB {
				growMin = GiB
			}
			continue
		}
		fixed += alignUp(p.SizeBytes, MiB)
	}
	plan := &Plan{SourceDisk: src.Name, SourceSizeBytes: src.SizeBytes, TargetSizeBytes: targetSizeBytes, SectorSize: sectorSize, MinimumBytes: fixed + growMin + 2*MiB}
	if targetSizeBytes < plan.MinimumBytes {
		return nil, &RefusalError{Reason: fmt.Sprintf("target is too small: %d bytes available, %d bytes needed (fixed partitions %d + root %d + GPT reserve)", targetSizeBytes, plan.MinimumBytes, fixed, growMin)}
	}
	usableEnd := targetSizeBytes - MiB
	cursor := MiB
	for i, p := range parts {
		size := alignUp(p.SizeBytes, MiB)
		grown := false
		if i == growIdx {
			var after int64
			for _, q := range parts[i+1:] {
				after += alignUp(q.SizeBytes, MiB)
			}
			size = usableEnd - after - cursor
			grown = true
		}
		plan.Partitions = append(plan.Partitions, PlannedPartition{
			Number: p.Number, Role: p.Role, TypeGUID: p.TypeGUID, PartUUID: p.PartUUID, Name: windowsPartitionName(p.Role),
			StartBytes: cursor, SizeBytes: size, Filesystem: strings.ToLower(p.Filesystem), FSUUID: p.FSUUID,
			Label: p.Label, MountPoint: p.MountPoint, Grown: grown, Attributes: p.Attributes,
		})
		cursor += size
	}
	if cursor > usableEnd {
		return nil, &RefusalError{Reason: fmt.Sprintf("target is too small: plan ends at %d bytes but only %d are usable", cursor, usableEnd)}
	}
	return plan, nil
}
