name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Breeze? We'd love to hear it.

        For broader discussions, consider using [GitHub Discussions](https://github.com/lanternops/breeze/discussions) instead.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's your use case?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've considered?

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Breeze would this affect?
      options:
        - Web Dashboard
        - API Server
        - Agent
        - Remote Access
        - Discovery / Scanning
        - Alerting / Notifications
        - Reporting
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How big of a change is this?
      options:
        - Small (UI tweak, config option)
        - Medium (new feature within existing module)
        - Large (new module or major change)
