import {
  agentBinariesStatus,
  databaseStatus,
  emailStatus,
  redisStatus,
  transportSecurityStatus,
  workspaceExtensionStatus,
} from './customStatus';
import { defineEntry } from './statusHelpers';
import type { ConnectionEntry } from './types';

/**
 * The curated connection registry (spec §1, D3). Every var is secret unless it
 * says `secret: false` (D8). Every `secret: false` line is reviewed in the PR.
 * The coverage ratchet (envInventory.test.ts) fails when an env name the API
 * reads is in neither this registry nor INTERNAL_ENV_VARS.
 */
export const CONNECTION_REGISTRY: readonly ConnectionEntry[] = [
  // ── core ────────────────────────────────────────────────────────────────
  defineEntry({
    id: 'database',
    group: 'core',
    label: 'PostgreSQL database',
    docsUrl: '/deploy/environment/#database',
    core: true,
    vars: [
      { name: 'DATABASE_URL', required: true },
      { name: 'DATABASE_URL_APP' },
      { name: 'BREEZE_APP_DB_PASSWORD' },
      { name: 'POSTGRES_PASSWORD' },
      { name: 'AUDIT_ADMIN_DATABASE_URL' },
    ],
    status: { kind: 'custom', fn: databaseStatus },
  }),
  defineEntry({
    id: 'redis',
    group: 'core',
    label: 'Redis',
    docsUrl: '/deploy/environment/#redis',
    core: true,
    vars: [
      { name: 'REDIS_URL' },
      { name: 'REDIS_HOST', secret: false },
      { name: 'REDIS_PORT', secret: false },
      { name: 'REDIS_PASSWORD' },
      { name: 'REDIS_PASSWORD_FILE' },
      { name: 'BREEZE_ALLOW_UNAUTH_REDIS', secret: false },
    ],
    status: { kind: 'custom', fn: redisStatus },
  }),
  defineEntry({
    id: 'public-urls',
    group: 'core',
    label: 'Public URLs',
    docsUrl: '/deploy/environment/#server',
    core: true,
    vars: [
      { name: 'PUBLIC_APP_URL', secret: false, required: true },
      { name: 'PUBLIC_API_URL', secret: false, required: true },
      { name: 'DASHBOARD_URL', secret: false },
      { name: 'PUBLIC_URL', secret: false },
      { name: 'PUBLIC_PORTAL_URL', secret: false },
      { name: 'PUBLIC_WEB_URL', secret: false },
      { name: 'API_URL', secret: false },
      { name: 'BREEZE_SERVER', secret: false },
      { name: 'PORTAL_BASE_PATH', secret: false },
      { name: 'PUBLIC_ACTIVATION_BASE_URL', secret: false },
      { name: 'CORS_ALLOWED_ORIGINS', secret: false },
      { name: 'CORS_INCLUDE_DEFAULT_ORIGINS', secret: false },
      { name: 'WEBAUTHN_ORIGIN', secret: false },
      { name: 'WEBAUTHN_RP_ID', secret: false },
      { name: 'WEBAUTHN_RP_NAME', secret: false },
    ],
  }),
  // ── email ───────────────────────────────────────────────────────────────
  defineEntry({
    id: 'email',
    group: 'email',
    label: 'Outbound email',
    docsUrl: '/deploy/environment/#email',
    core: true,
    vars: [
      { name: 'EMAIL_PROVIDER', secret: false },
      { name: 'EMAIL_FROM', secret: false },
      { name: 'RESEND_API_KEY' },
      { name: 'SMTP_HOST', secret: false },
      { name: 'SMTP_PORT', secret: false },
      { name: 'SMTP_SECURE', secret: false },
      { name: 'SMTP_TIMEOUT_MS', secret: false },
      { name: 'SMTP_USER' },
      { name: 'SMTP_PASS' },
      { name: 'SMTP_FROM', secret: false },
      { name: 'MAILGUN_API_KEY' },
      { name: 'MAILGUN_DOMAIN', secret: false },
      { name: 'MAILGUN_FROM', secret: false },
      { name: 'MAILGUN_BASE_URL', secret: false },
      { name: 'MAILGUN_TIMEOUT_MS', secret: false },
      { name: 'EMAIL_SUPPORT_ADDRESS', secret: false },
    ],
    status: { kind: 'custom', fn: emailStatus },
  }),
  defineEntry({
    id: 'partner-sending-domains',
    group: 'email',
    label: 'Partner sending domains',
    docsUrl: '/deploy/custom-sender-addresses/',
    vars: [
      { name: 'EMAIL_DOMAINS_PROVIDER', secret: false, required: true },
      { name: 'EMAIL_DOMAINS_RESEND_API_KEY' },
      { name: 'EMAIL_DOMAINS_RESEND_SENDING_KEY' },
      { name: 'EMAIL_DOMAINS_WEBHOOK_SECRET' },
      { name: 'EMAIL_DOMAINS_REGION', secret: false },
      { name: 'EMAIL_DOMAINS_STATIC_ALLOWED', secret: false },
    ],
  }),
  defineEntry({
    id: 'inbound-ticket-email',
    group: 'email',
    label: 'Inbound email-to-ticket (Mailgun)',
    docsUrl: '/deploy/environment/#inbound-email-to-ticket-mailgun',
    vars: [
      { name: 'TICKETS_INBOUND_DOMAIN', secret: false, required: true },
      { name: 'MAILGUN_INBOUND_SIGNING_KEY', required: true },
    ],
  }),
  // ── storage-backups ─────────────────────────────────────────────────────
  defineEntry({
    id: 'object-storage',
    group: 'storage-backups',
    label: 'S3-compatible object storage',
    docsUrl: '/deploy/environment/#object-storage',
    vars: [
      { name: 'S3_BUCKET', secret: false, required: true },
      { name: 'S3_ACCESS_KEY', required: true },
      { name: 'S3_SECRET_KEY', required: true },
      { name: 'S3_ENDPOINT', secret: false },
      { name: 'S3_REGION', secret: false },
      { name: 'ARTIFACT_BLOB_BACKEND', secret: false },
      { name: 'BREEZE_AI_ARTIFACT_CAPTURE_ENABLED', secret: false },
      { name: 'ARTIFACT_S3_ACCESS_KEY' },
      { name: 'ARTIFACT_S3_SECRET_KEY' },
      { name: 'ARTIFACT_S3_BUCKET_US', secret: false },
      { name: 'ARTIFACT_S3_BUCKET_EU', secret: false },
      { name: 'ARTIFACT_S3_ENDPOINT_US', secret: false },
      { name: 'ARTIFACT_S3_ENDPOINT_EU', secret: false },
      { name: 'ARTIFACT_S3_REGION_US', secret: false },
      { name: 'ARTIFACT_S3_REGION_EU', secret: false },
      { name: 'ARTIFACT_S3_SSE', secret: false },
    ],
  }),
  defineEntry({
    id: 'backup-failover-url',
    group: 'storage-backups',
    label: 'Backup control-plane failover URL',
    docsUrl: '/deploy/environment/#backup-enterprise-agent-backup',
    vars: [
      { name: 'AGENT_BACKUP_SERVER_URL', secret: false, required: true },
    ],
  }),
  defineEntry({
    id: 'recovery-media-signing',
    group: 'storage-backups',
    label: 'Bare-metal recovery media signing',
    vars: [
      { name: 'RECOVERY_SIGNING_PRIVATE_KEY', required: true },
      { name: 'RECOVERY_SIGNING_PUBLIC_KEY' },
      { name: 'RECOVERY_SIGNING_KEY_ID' },
      { name: 'RECOVERY_SIGNING_KEYS_JSON' },
    ],
  }),
  defineEntry({
    id: 'c2c-m365-backup',
    group: 'storage-backups',
    label: 'Microsoft 365 cloud-to-cloud backup app',
    docsUrl: '/deploy/environment/#cloud-to-cloud-backup-m365',
    vars: [
      { name: 'C2C_M365_CLIENT_ID', secret: false, required: true },
      { name: 'C2C_M365_CLIENT_SECRET', required: true },
    ],
  }),
  // ── ai ──────────────────────────────────────────────────────────────────
  defineEntry({
    id: 'anthropic',
    group: 'ai',
    label: 'Anthropic (platform AI key)',
    docsUrl: '/deploy/environment/#ai',
    vars: [
      { name: 'ANTHROPIC_API_KEY', required: true },
      { name: 'ANTHROPIC_AUTH_TOKEN' },
      { name: 'ANTHROPIC_BASE_URL', secret: false },
      { name: 'ANTHROPIC_MODEL', secret: false },
    ],
  }),
  defineEntry({
    id: 'openai-compatible-llm',
    group: 'ai',
    label: 'Alternative LLM backend (OpenAI-compatible)',
    docsUrl: '/deploy/environment/#self-hosted-alternative-anthropic-compatible-backends',
    vars: [
      { name: 'MCP_LLM_BASE_URL', secret: false, required: true },
      { name: 'MCP_LLM_PROVIDER', secret: false },
      { name: 'MCP_LLM_API_KEY' },
      { name: 'MCP_LLM_MODEL', secret: false },
      { name: 'MCP_LLM_PRICE_INPUT_PER_M_USD', secret: false },
      { name: 'MCP_LLM_PRICE_OUTPUT_PER_M_USD', secret: false },
    ],
  }),
  defineEntry({
    id: 'llm-provider-catalog',
    group: 'ai',
    label: 'LLM provider catalog',
    vars: [
      { name: 'LLM_PROVIDER_CATALOG_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['LLM_PROVIDER_CATALOG_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'ai-agents',
    group: 'ai',
    label: 'AI agents',
    docsUrl: '/deploy/environment/#ai-operator-preview-off-by-default',
    vars: [
      { name: 'BREEZE_AI_AGENTS_ENABLED', secret: false },
      { name: 'BREEZE_AI_AGENTS_POLICY_DECIDE_ENABLED', secret: false },
      { name: 'BREEZE_AI_AGENTS_SWEEP_ACT_ENABLED', secret: false },
      { name: 'BREEZE_AI_SCRIPT_AUTHORING_ENABLED', secret: false },
      { name: 'BREEZE_AI_SCRIPT_REVIEWER_MODEL', secret: false },
      { name: 'AI_OPERATOR_TASKS_ENABLED', secret: false },
      { name: 'AI_OPERATOR_RECIPE_SERVICE_RECOVERY_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['BREEZE_AI_AGENTS_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'ai-workspace-sandbox',
    group: 'ai',
    label: 'AI workspace sandbox',
    vars: [
      { name: 'BREEZE_AI_WORKSPACE_ENABLED', secret: false },
      { name: 'AI_WORKSPACE_BACKEND', secret: false },
      { name: 'VERCEL_SANDBOX_TOKEN' },
      { name: 'VERCEL_TEAM_ID' },
      { name: 'VERCEL_PROJECT_ID' },
      { name: 'VERCEL_SANDBOX_IMAGE', secret: false },
      { name: 'VERCEL_SANDBOX_REGION_US', secret: false },
      { name: 'VERCEL_SANDBOX_REGION_EU', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['BREEZE_AI_WORKSPACE_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'workspace-extension',
    group: 'ai',
    label: 'Workspace extension (pgvector)',
    vars: [
      { name: 'BREEZE_WORKSPACE_ENABLED', secret: false },
    ],
    status: { kind: 'custom', fn: workspaceExtensionStatus },
  }),
  defineEntry({
    id: 'tool-sources',
    group: 'ai',
    label: 'External MCP tool sources',
    vars: [
      { name: 'TOOL_SOURCES_ENABLED', secret: false },
      { name: 'TOOL_SOURCES_ALLOW_PRIVATE_EGRESS', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['TOOL_SOURCES_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  // ── billing ─────────────────────────────────────────────────────────────
  defineEntry({
    id: 'breeze-billing',
    group: 'billing',
    label: 'Breeze billing service',
    docsUrl: '/deploy/environment/#billing',
    vars: [
      { name: 'BREEZE_BILLING_URL', secret: false, required: true },
      { name: 'BREEZE_BILLING_API_KEY', required: true },
      { name: 'BILLING_URL', secret: false },
    ],
  }),
  defineEntry({
    id: 'ai-cost-billing',
    group: 'billing',
    label: 'AI usage metering',
    vars: [
      { name: 'BILLING_SERVICE_URL', secret: false, required: true },
      { name: 'BILLING_SERVICE_API_KEY', required: true },
    ],
  }),
  defineEntry({
    id: 'stripe',
    group: 'billing',
    label: 'Stripe',
    vars: [
      { name: 'STRIPE_SECRET_KEY', required: true },
      { name: 'STRIPE_WEBHOOK_SECRET', required: true },
      { name: 'STRIPE_SESSION_REVOCATION_MODE', secret: false },
      { name: 'STRIPE_ACCOUNT_CACHE_REFRESH_ENABLED', secret: false },
    ],
  }),
  defineEntry({
    id: 'quickbooks',
    group: 'billing',
    label: 'QuickBooks Online',
    docsUrl: '/deploy/environment/#accounting-quickbooks-online',
    vars: [
      { name: 'QBO_CLIENT_ID', secret: false, required: true },
      { name: 'QBO_CLIENT_SECRET', required: true },
      { name: 'QBO_REDIRECT_URI', secret: false },
      { name: 'QBO_ENVIRONMENT', secret: false },
      { name: 'QBO_WEBHOOK_VERIFIER_TOKEN' },
    ],
  }),
  // ── microsoft-365 ───────────────────────────────────────────────────────
  defineEntry({
    id: 'm365-identity-tools',
    group: 'microsoft-365',
    label: 'Microsoft 365 identity tools',
    vars: [
      { name: 'M365_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['M365_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'm365-tenant-sync',
    group: 'microsoft-365',
    label: 'Microsoft 365 tenant sync',
    docsUrl: '/deploy/environment/#api-side-tenant-sync',
    vars: [
      { name: 'M365_TENANT_SYNC_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['M365_TENANT_SYNC_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'm365-graph-read',
    group: 'microsoft-365',
    label: 'Customer Graph read (executor)',
    docsUrl: '/deploy/environment/#customer-microsoft-365-graph-read-consent-optional',
    vars: [
      { name: 'M365_CUSTOMER_GRAPH_READ_ONBOARDING_ENABLED', secret: false },
      { name: 'M365_GRAPH_READ_TOOLS_ENABLED', secret: false },
      { name: 'M365_CUSTOMER_GRAPH_READ_CLIENT_ID', secret: false },
      { name: 'M365_CUSTOMER_GRAPH_READ_CREDENTIAL_VERSION' },
      { name: 'M365_CUSTOMER_GRAPH_READ_VAULT_REF' },
      { name: 'M365_GRAPH_READ_EXECUTOR_URL' },
      { name: 'M365_GRAPH_READ_EXECUTOR_AUDIENCE', secret: false },
      { name: 'M365_GRAPH_READ_EXECUTOR_SIGNING_KID' },
      { name: 'M365_GRAPH_READ_EXECUTOR_SIGNING_PRIVATE_JWK_FILE' },
      { name: 'M365_CUSTOMER_GRAPH_READ_ONBOARDING_ORG_IDS', secret: false },
      { name: 'M365_GRAPH_READ_TOOLS_ORG_IDS', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['M365_CUSTOMER_GRAPH_READ_ONBOARDING_ENABLED', 'M365_GRAPH_READ_TOOLS_ENABLED'],
      requiredWhenOn: [
        'M365_CUSTOMER_GRAPH_READ_CLIENT_ID',
        'M365_CUSTOMER_GRAPH_READ_CREDENTIAL_VERSION',
        'M365_CUSTOMER_GRAPH_READ_VAULT_REF',
        'M365_GRAPH_READ_EXECUTOR_URL',
        'M365_GRAPH_READ_EXECUTOR_AUDIENCE',
        'M365_GRAPH_READ_EXECUTOR_SIGNING_KID',
        'M365_GRAPH_READ_EXECUTOR_SIGNING_PRIVATE_JWK_FILE',
      ],
    },
  }),
  defineEntry({
    id: 'm365-graph-actions',
    group: 'microsoft-365',
    label: 'Customer Graph actions (write executor)',
    docsUrl: '/deploy/environment/#customer-microsoft-365-graph-actions-write-executor-optional',
    vars: [
      { name: 'M365_CUSTOMER_GRAPH_ACTIONS_ONBOARDING_ENABLED', secret: false },
      { name: 'M365_GRAPH_ACTIONS_TOOLS_ENABLED', secret: false },
      { name: 'M365_CUSTOMER_GRAPH_ACTIONS_CLIENT_ID', secret: false },
      { name: 'M365_CUSTOMER_GRAPH_ACTIONS_CREDENTIAL_VERSION' },
      { name: 'M365_CUSTOMER_GRAPH_ACTIONS_VAULT_REF' },
      { name: 'M365_GRAPH_ACTIONS_EXECUTOR_URL' },
      { name: 'M365_GRAPH_ACTIONS_EXECUTOR_AUDIENCE', secret: false },
      { name: 'M365_GRAPH_ACTIONS_EXECUTOR_SIGNING_KID' },
      { name: 'M365_GRAPH_ACTIONS_EXECUTOR_SIGNING_PRIVATE_JWK_FILE' },
      { name: 'M365_CUSTOMER_GRAPH_ACTIONS_ONBOARDING_ORG_IDS', secret: false },
      { name: 'M365_GRAPH_ACTIONS_TOOLS_ORG_IDS', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['M365_CUSTOMER_GRAPH_ACTIONS_ONBOARDING_ENABLED', 'M365_GRAPH_ACTIONS_TOOLS_ENABLED'],
      requiredWhenOn: [
        'M365_CUSTOMER_GRAPH_ACTIONS_CLIENT_ID',
        'M365_CUSTOMER_GRAPH_ACTIONS_CREDENTIAL_VERSION',
        'M365_CUSTOMER_GRAPH_ACTIONS_VAULT_REF',
        'M365_GRAPH_ACTIONS_EXECUTOR_URL',
        'M365_GRAPH_ACTIONS_EXECUTOR_AUDIENCE',
        'M365_GRAPH_ACTIONS_EXECUTOR_SIGNING_KID',
        'M365_GRAPH_ACTIONS_EXECUTOR_SIGNING_PRIVATE_JWK_FILE',
      ],
    },
  }),
  defineEntry({
    id: 'm365-comms',
    group: 'microsoft-365',
    label: 'Microsoft 365 comms (executor)',
    vars: [
      { name: 'M365_COMMS_ONBOARDING_ENABLED', secret: false },
      { name: 'M365_COMMS_TOOLS_ENABLED', secret: false },
      { name: 'M365_COMMS_CLIENT_ID', secret: false },
      { name: 'M365_COMMS_EXECUTOR_URL' },
      { name: 'M365_COMMS_EXECUTOR_AUDIENCE', secret: false },
      { name: 'M365_COMMS_EXECUTOR_SIGNING_KID' },
      { name: 'M365_COMMS_EXECUTOR_SIGNING_PRIVATE_JWK_FILE' },
      { name: 'M365_COMMS_ONBOARDING_USER_IDS', secret: false },
      { name: 'M365_COMMS_TOOLS_USER_IDS', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['M365_COMMS_ONBOARDING_ENABLED', 'M365_COMMS_TOOLS_ENABLED'],
      requiredWhenOn: [
        'M365_COMMS_CLIENT_ID',
        'M365_COMMS_EXECUTOR_URL',
        'M365_COMMS_EXECUTOR_AUDIENCE',
        'M365_COMMS_EXECUTOR_SIGNING_KID',
        'M365_COMMS_EXECUTOR_SIGNING_PRIVATE_JWK_FILE',
      ],
    },
  }),
  defineEntry({
    id: 'ticket-mailbox-m365',
    group: 'microsoft-365',
    label: 'Ticket mailbox (Microsoft 365)',
    docsUrl: '/deploy/environment/#ticket-mailbox-m365-email-to-ticket',
    vars: [
      { name: 'TICKET_MAILBOX_M365_CLIENT_ID', secret: false, required: true },
      { name: 'TICKET_MAILBOX_M365_CLIENT_SECRET', required: true },
    ],
  }),
  // ── identity-sso ────────────────────────────────────────────────────────
  defineEntry({
    id: 'signing-keys',
    group: 'identity-sso',
    label: 'Signing and encryption keys',
    docsUrl: '/deploy/environment/#authentication--security',
    core: true,
    vars: [
      { name: 'JWT_SECRET', required: true },
      { name: 'APP_ENCRYPTION_KEY', required: true },
      { name: 'MFA_ENCRYPTION_KEY', required: true },
      { name: 'JWT_SIGNING_KEYRING' },
      { name: 'JWT_ACTIVE_KID' },
      { name: 'APP_ENCRYPTION_KEY_ID' },
      { name: 'APP_ENCRYPTION_KEYRING' },
      { name: 'SECRET_ENCRYPTION_KEY' },
      { name: 'SECRET_ENCRYPTION_KEYRING' },
      { name: 'SECRET_ENCRYPTION_KEY_ID' },
      { name: 'SSO_ENCRYPTION_KEY' },
      { name: 'SESSION_SECRET' },
      { name: 'PARTNER_API_CURSOR_SIGNING_KEY' },
      { name: 'ENROLLMENT_KEY_PEPPER' },
      { name: 'MFA_RECOVERY_CODE_PEPPER' },
    ],
  }),
  defineEntry({
    id: 'agent-enrollment-secret',
    group: 'identity-sso',
    label: 'Agent enrollment secret',
    vars: [
      { name: 'AGENT_ENROLLMENT_SECRET', required: true },
      { name: 'ENROLLMENT_SECRET_ENFORCEMENT_MODE', secret: false },
    ],
  }),
  defineEntry({
    id: 'cloudflare-access',
    group: 'identity-sso',
    label: 'Cloudflare Access trust',
    docsUrl: '/deploy/cloudflare-access-trust/',
    vars: [
      { name: 'CF_ACCESS_TRUST_ENABLED', secret: false },
      { name: 'CF_ACCESS_TEAM_DOMAIN', secret: false },
      { name: 'CF_ACCESS_AUD' },
      { name: 'CF_ACCESS_TRUSTS_MFA', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['CF_ACCESS_TRUST_ENABLED'],
      requiredWhenOn: [
        'CF_ACCESS_TEAM_DOMAIN',
        'CF_ACCESS_AUD',
      ],
    },
  }),
  defineEntry({
    id: 'client-ai-entra',
    group: 'identity-sso',
    label: 'Breeze AI for Office (Entra app)',
    docsUrl: '/deploy/environment/#breeze-ai-for-office-add-ins-optional',
    vars: [
      { name: 'CLIENT_AI_ENTRA_CLIENT_ID', secret: false, required: true },
    ],
  }),
  defineEntry({
    id: 'twilio',
    group: 'identity-sso',
    label: 'Twilio SMS',
    docsUrl: '/deploy/environment/#sms-twilio',
    vars: [
      { name: 'TWILIO_ACCOUNT_SID', required: true },
      { name: 'TWILIO_AUTH_TOKEN', required: true },
      { name: 'TWILIO_MESSAGING_SERVICE_SID' },
      { name: 'TWILIO_VERIFY_SERVICE_SID' },
      { name: 'TWILIO_PHONE_NUMBER', secret: false },
    ],
  }),
  defineEntry({
    id: 'mobile-attestation',
    group: 'identity-sso',
    label: 'Mobile app attestation',
    vars: [
      { name: 'PLAY_INTEGRITY_SERVICE_ACCOUNT', required: true },
      { name: 'APPLE_APP_ATTEST_APP_ID', secret: false, required: true },
      { name: 'APPLE_APP_ATTEST_ENVIRONMENT', secret: false },
      { name: 'BREEZE_AUTHENTICATOR_ATTESTATION_ENFORCED', secret: false },
    ],
  }),
  // ── remote-access ───────────────────────────────────────────────────────
  defineEntry({
    id: 'turn',
    group: 'remote-access',
    label: 'TURN relay',
    docsUrl: '/deploy/turn-server/',
    vars: [
      { name: 'TURN_HOST', secret: false, required: true },
      { name: 'TURN_SECRET', required: true },
      { name: 'TURN_PORT', secret: false },
      { name: 'TURN_TLS_HOST', secret: false },
      { name: 'TURN_TLS_PORT', secret: false },
      { name: 'TURN_TLS_DIR', secret: false },
    ],
  }),
  // ── agent-releases ──────────────────────────────────────────────────────
  defineEntry({
    id: 'agent-binaries',
    group: 'agent-releases',
    label: 'Agent binary source',
    docsUrl: '/deploy/binaries/',
    vars: [
      { name: 'BINARY_SOURCE', secret: false },
      { name: 'BINARY_GITHUB_REPOSITORY', secret: false },
      { name: 'GITHUB_REPO', secret: false },
      { name: 'BINARY_VERSION', secret: false },
      { name: 'BREEZE_VERSION', secret: false },
      { name: 'BINARY_EDITION', secret: false },
      { name: 'AGENT_AUTO_PROMOTE', secret: false },
      { name: 'GITHUB_TOKEN' },
      { name: 'GH_TOKEN' },
    ],
    status: { kind: 'custom', fn: agentBinariesStatus },
  }),
  defineEntry({
    id: 'update-manifest-signing',
    group: 'agent-releases',
    label: 'Update manifest signing keys',
    docsUrl: '/deploy/code-signing/',
    vars: [
      { name: 'AGENT_UPDATE_MANIFEST_PUBLIC_KEYS' },
      { name: 'BREEZE_UPDATE_MANIFEST_PUBLIC_KEYS' },
      { name: 'RELEASE_ARTIFACT_MANIFEST_PUBLIC_KEYS' },
      { name: 'BREEZE_RELEASE_ARTIFACT_MANIFEST_PUBLIC_KEYS' },
      { name: 'RELEASE_ARTIFACT_MANIFEST_VERIFICATION', secret: false },
      { name: 'AGENT_REQUIRE_MANIFEST_SIGNING_KEY_ID' },
    ],
    status: {
      kind: 'anyOf',
      names: [
        'AGENT_UPDATE_MANIFEST_PUBLIC_KEYS',
        'BREEZE_UPDATE_MANIFEST_PUBLIC_KEYS',
        'RELEASE_ARTIFACT_MANIFEST_PUBLIC_KEYS',
        'BREEZE_RELEASE_ARTIFACT_MANIFEST_PUBLIC_KEYS',
      ],
    },
  }),
  // ── observability ───────────────────────────────────────────────────────
  defineEntry({
    id: 'sentry',
    group: 'observability',
    label: 'Sentry',
    docsUrl: '/security/error-tracking/',
    vars: [
      { name: 'SENTRY_DSN', required: true },
      { name: 'SENTRY_ENVIRONMENT', secret: false },
      { name: 'SENTRY_TRACES_SAMPLE_RATE', secret: false },
      { name: 'SENTRY_PROFILES_SAMPLE_RATE', secret: false },
    ],
  }),
  defineEntry({
    id: 'metrics-scrape',
    group: 'observability',
    label: 'Prometheus metrics scrape',
    docsUrl: '/monitoring/stack/',
    vars: [
      { name: 'METRICS_SCRAPE_TOKEN', required: true },
      { name: 'METRICS_SCRAPE_IP_ALLOWLIST', secret: false },
    ],
  }),
  defineEntry({
    id: 'ops-alerts',
    group: 'observability',
    label: 'Operator alerts',
    vars: [
      { name: 'OPS_ALERT_EMAIL', secret: false },
      { name: 'OPS_ALERT_WEBHOOK_URL' },
      { name: 'OPS_ALERT_LABEL', secret: false },
    ],
    status: {
      kind: 'anyOf',
      names: [
        'OPS_ALERT_EMAIL',
        'OPS_ALERT_WEBHOOK_URL',
      ],
    },
  }),
  defineEntry({
    id: 'csp-reporting',
    group: 'observability',
    label: 'CSP violation reporting',
    vars: [
      { name: 'CSP_REPORT_URI', required: true },
    ],
  }),
  // ── security-abuse ──────────────────────────────────────────────────────
  defineEntry({
    id: 'transport-security',
    group: 'security-abuse',
    label: 'HTTPS and proxy trust',
    docsUrl: '/deploy/tls/',
    vars: [
      { name: 'FORCE_HTTPS', secret: false },
      { name: 'TRUST_PROXY_HEADERS', secret: false },
      { name: 'TRUSTED_PROXY_CIDRS', secret: false },
      { name: 'TRUST_CF_CONNECTING_IP', secret: false },
    ],
    status: { kind: 'custom', fn: transportSecurityStatus },
  }),
  defineEntry({
    id: 'cloudflare-mtls',
    group: 'security-abuse',
    label: 'Cloudflare mTLS for agents',
    docsUrl: '/security/mtls/',
    vars: [
      { name: 'CLOUDFLARE_API_TOKEN', required: true },
      { name: 'CLOUDFLARE_ZONE_ID', required: true },
      { name: 'AGENT_MTLS_BINDING_MODE', secret: false },
    ],
  }),
  defineEntry({
    id: 'abuse-signals',
    group: 'security-abuse',
    label: 'Signup abuse signals',
    vars: [
      { name: 'ABUSE_SIGNALS_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['ABUSE_SIGNALS_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'ip-classify',
    group: 'security-abuse',
    label: 'IP reputation lookup',
    vars: [
      { name: 'IP_CLASSIFY_PROVIDER', secret: false, required: true },
      { name: 'IP_CLASSIFY_API_KEY' },
    ],
  }),
  defineEntry({
    id: 'sensitive-data-keys',
    group: 'security-abuse',
    label: 'Sensitive-data encryption keys',
    vars: [
      { name: 'SENSITIVE_DATA_ENCRYPTION_KEY_B64' },
      { name: 'SENSITIVE_DATA_KEYRING_JSON' },
      { name: 'SENSITIVE_DATA_ENCRYPTION_KEY_REF' },
      { name: 'SENSITIVE_DATA_ENCRYPTION_KEY_VERSION' },
    ],
    status: {
      kind: 'anyOf',
      names: [
        'SENSITIVE_DATA_ENCRYPTION_KEY_B64',
        'SENSITIVE_DATA_KEYRING_JSON',
      ],
    },
  }),
  defineEntry({
    id: 'audit-anchor-signing',
    group: 'security-abuse',
    label: 'Audit-chain anchor signing',
    vars: [
      { name: 'AUDIT_ANCHOR_SIGNING_KEY', required: true },
    ],
  }),
  // ── integrations ────────────────────────────────────────────────────────
  defineEntry({
    id: 'delegant',
    group: 'integrations',
    label: 'Delegant',
    vars: [
      { name: 'DELEGANT_BASE_URL', secret: false, required: true },
      { name: 'DELEGANT_SERVICE_TOKEN', required: true },
      { name: 'DELEGANT_PRINCIPAL_KID' },
      { name: 'DELEGANT_PRINCIPAL_SIGNING_KEY' },
      { name: 'DELEGANT_AGENT_ID' },
      { name: 'DELEGANT_ACTING_USER_ID' },
    ],
  }),
  defineEntry({
    id: 'mcp-oauth',
    group: 'integrations',
    label: 'MCP server OAuth',
    docsUrl: '/deploy/environment/#mcp-server',
    vars: [
      { name: 'MCP_OAUTH_ENABLED', secret: false },
      { name: 'OAUTH_ISSUER', secret: false },
      { name: 'OAUTH_RESOURCE_URL', secret: false },
      { name: 'OAUTH_CONSENT_URL_BASE', secret: false },
      { name: 'OAUTH_COOKIE_SECRET' },
      { name: 'OAUTH_JWKS_PRIVATE_JWK' },
      { name: 'OAUTH_JWKS_PUBLIC_JWK' },
      { name: 'OAUTH_DCR_ENABLED', secret: false },
      { name: 'OAUTH_DCR_ALLOW_ANONYMOUS', secret: false },
      { name: 'OAUTH_DCR_REQUIRE_IAT', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['MCP_OAUTH_ENABLED'],
      requiredWhenOn: [
        'OAUTH_COOKIE_SECRET',
        'OAUTH_JWKS_PRIVATE_JWK',
      ],
    },
  }),
  defineEntry({
    id: 'google-workspace-tools',
    group: 'integrations',
    label: 'Google Workspace tools',
    vars: [
      { name: 'GOOGLE_WORKSPACE_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['GOOGLE_WORKSPACE_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'partner-hooks',
    group: 'integrations',
    label: 'Partner lifecycle hooks',
    vars: [
      { name: 'PARTNER_HOOKS_URL', required: true },
      { name: 'PARTNER_HOOKS_SECRET', required: true },
    ],
  }),
  defineEntry({
    id: 'apns',
    group: 'integrations',
    label: 'Apple push notifications (APNs)',
    docsUrl: '/deploy/environment/#mobile-push-notifications-ios',
    vars: [
      { name: 'APNS_AUTH_KEY', required: true },
      { name: 'APNS_KEY_ID', required: true },
      { name: 'APNS_TEAM_ID', secret: false, required: true },
      { name: 'APNS_BUNDLE_ID', secret: false },
      { name: 'APNS_ENVIRONMENT', secret: false },
    ],
  }),
  defineEntry({
    id: 'fcm',
    group: 'integrations',
    label: 'Firebase Cloud Messaging',
    docsUrl: '/deploy/environment/#mobile-push-notifications-android',
    vars: [
      { name: 'FIREBASE_SERVICE_ACCOUNT', required: true },
    ],
  }),
  defineEntry({
    id: 'warranty-dell',
    group: 'integrations',
    label: 'Dell warranty lookup',
    docsUrl: '/deploy/environment/#warranty-lookups',
    vars: [
      // Client-credentials id (never in a public consent URL): secret by default.
      { name: 'DELL_CLIENT_ID', required: true },
      { name: 'DELL_CLIENT_SECRET', required: true },
    ],
  }),
  defineEntry({
    id: 'warranty-lenovo',
    group: 'integrations',
    label: 'Lenovo warranty lookup',
    docsUrl: '/deploy/environment/#warranty-lookups',
    vars: [
      { name: 'LENOVO_API_KEY', required: true },
      { name: 'LENOVO_WARRANTY_ENABLED', secret: false },
    ],
  }),
  defineEntry({
    id: 'warranty-hp',
    group: 'integrations',
    label: 'HP warranty lookup',
    docsUrl: '/deploy/environment/#warranty-lookups',
    vars: [
      { name: 'HP_WARRANTY_ENABLED', secret: false },
    ],
    status: {
      kind: 'flags',
      flags: ['HP_WARRANTY_ENABLED'],
      requiredWhenOn: [],
    },
  }),
  defineEntry({
    id: 'nvd',
    group: 'integrations',
    label: 'NVD vulnerability feed',
    docsUrl: '/deploy/environment/#vulnerability-management',
    vars: [
      { name: 'NVD_API_KEY', required: true },
    ],
  }),
];

/**
 * Invariant 3: a `secret: false` var whose name matches SECRET_NAME_PATTERN
 * must be listed here with the reason its value is safe to show.
 */
export const SECRET_NAME_PATTERN =
  /SECRET|KEY|TOKEN|PASS|PRIVATE|DSN|CREDENTIAL|URL|URI|ENDPOINT|SERVICE_ACCOUNT|JWK|SID|WEBHOOK|SIGNING|CERT|SALT|SEED|ENCRYPT|JSON|B64|BASE64/;

export const SECRET_NAME_EXCEPTIONS: Readonly<Record<string, string>> = {
  PUBLIC_APP_URL: 'public web-app origin, shown to operators already in every email link',
  PUBLIC_API_URL: 'public API origin, embedded in agent installers',
  DASHBOARD_URL: 'public web-app origin (legacy alias of PUBLIC_APP_URL)',
  PUBLIC_URL: 'public origin fallback for OAuth/SSO callbacks',
  PUBLIC_PORTAL_URL: 'public customer-portal origin',
  PUBLIC_WEB_URL: 'public web-app origin for support-session links',
  API_URL: 'public API origin override for agent downloads',
  PUBLIC_ACTIVATION_BASE_URL: 'public activation-landing origin',
  MAILGUN_BASE_URL: 'public Mailgun API base (US or EU region)',
  S3_ENDPOINT: 'object-storage endpoint host; values with URL userinfo are refused at runtime',
  ARTIFACT_S3_ENDPOINT_US: 'object-storage endpoint host; values with URL userinfo are refused at runtime',
  ARTIFACT_S3_ENDPOINT_EU: 'object-storage endpoint host; values with URL userinfo are refused at runtime',
  AGENT_BACKUP_SERVER_URL: 'public failover URL that is pushed to every agent',
  ANTHROPIC_BASE_URL: 'LLM gateway base URL; values with URL userinfo are refused at runtime',
  MCP_LLM_BASE_URL: 'LLM gateway base URL; values with URL userinfo are refused at runtime',
  TOOL_SOURCES_ALLOW_PRIVATE_EGRESS: 'boolean flag; "PRIVATE" names the network class, not a key',
  BREEZE_BILLING_URL: 'billing service base URL; values with URL userinfo are refused at runtime',
  BILLING_URL: 'public payment-setup landing URL',
  BILLING_SERVICE_URL: 'metering service base URL; values with URL userinfo are refused at runtime',
  QBO_REDIRECT_URI: 'public OAuth redirect URI registered with Intuit',
  ENROLLMENT_SECRET_ENFORCEMENT_MODE: 'enum (enforce/warn); "SECRET" names the thing it enforces',
  DELEGANT_BASE_URL: 'Delegant service base URL; values with URL userinfo are refused at runtime',
  OAUTH_RESOURCE_URL: 'public OAuth resource identifier',
  OAUTH_CONSENT_URL_BASE: 'public OAuth consent page origin',
};
