import type { AutopayCancelSource, AutopayNeedsAttentionReason, AutopayPaymentMethodType, CardFundingType, AccountHolderType, ConsentSource, AutopayIneligibleReason, CollectionFailureClass, CollectionAttemptInitiator } from '@breeze/shared';
import { pgTable, uuid, text, boolean, integer, numeric, jsonb, date, timestamp, char, pgEnum, check, unique, uniqueIndex, index, foreignKey } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { organizations, partners } from './orgs';
import { users } from './users';
import { invoices } from './invoices';
import { stripeConnectAccounts, invoiceStripePayments } from './stripePayments';
import { AUTOPAY_ENROLLMENT_STATUSES, AUTOPAY_SCHEDULE_STATES, COLLECTION_ATTEMPT_STATES, BILLING_NOTICE_KINDS, BILLING_NOTICE_STATUSES, BILLING_LINK_PURPOSES, ORG_PAYMENT_METHOD_STATUSES, ACH_MODES, AUTOPAY_OFFSET_RULES } from '@breeze/shared';
export const autopayEnrollmentStatusEnum = pgEnum('autopay_enrollment_status', [...AUTOPAY_ENROLLMENT_STATUSES]);
export const autopayScheduleStateEnum = pgEnum('autopay_schedule_state', [...AUTOPAY_SCHEDULE_STATES]);
export const collectionAttemptStateEnum = pgEnum('collection_attempt_state', [...COLLECTION_ATTEMPT_STATES]);
export const billingNoticeKindEnum = pgEnum('billing_notice_kind', [...BILLING_NOTICE_KINDS]);
export const billingNoticeStatusEnum = pgEnum('billing_notice_status', [...BILLING_NOTICE_STATUSES]);
export const billingLinkPurposeEnum = pgEnum('billing_link_purpose', [...BILLING_LINK_PURPOSES]);
export const orgPaymentMethodStatusEnum = pgEnum('org_payment_method_status', [...ORG_PAYMENT_METHOD_STATUSES]);
export const achModeEnum = pgEnum('ach_mode', [...ACH_MODES]);
export const autopayOffsetRuleEnum = pgEnum('autopay_offset_rule', [...AUTOPAY_OFFSET_RULES]);

export const billingPaymentSettings = pgTable('billing_payment_settings', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').references(() => organizations.id),
  partnerId: uuid('partner_id').references(() => partners.id),
  autopayOffsetDays: integer('autopay_offset_days'),
  autopayOffsetRule: autopayOffsetRuleEnum('autopay_offset_rule'),
  autopayCapEnabled: boolean('autopay_cap_enabled'),
  autopayCapAmount: numeric('autopay_cap_amount', { precision: 12, scale: 2 }),
  autopayCapCurrency: char('autopay_cap_currency', { length: 3 }),
  achMode: achModeEnum('ach_mode'),
  cardFeeBps: integer('card_fee_bps'),
  achFeeAmount: numeric('ach_fee_amount', { precision: 12, scale: 2 }),
  feeAttestedBy: uuid('fee_attested_by').references(() => users.id),
  feeAttestedAt: timestamp('fee_attested_at', { withTimezone: true }),
  remindersEnabled: boolean('reminders_enabled'),
  reminderBeforeDueDays: integer('reminder_before_due_days'),
  reminderRepeatDays: integer('reminder_repeat_days'),
  overdueReminderEveryDays: integer('overdue_reminder_every_days'),
}, (t) => [
  check('billing_payment_settings_autopay_offset_days_check', sql`${t.autopayOffsetDays} BETWEEN 0 AND 60`),
  check('billing_payment_settings_card_fee_bps_check', sql`${t.cardFeeBps} BETWEEN 0 AND 300`),
  check('billing_payment_settings_ach_fee_amount_check', sql`${t.achFeeAmount} BETWEEN 0 AND 25`),
  check('billing_payment_settings_reminder_before_due_days_check', sql`${t.reminderBeforeDueDays} BETWEEN 1 AND 31`),
  check('billing_payment_settings_reminder_repeat_days_check', sql`${t.reminderRepeatDays} BETWEEN 1 AND 31`),
  check('billing_payment_settings_overdue_reminder_every_days_check', sql`${t.overdueReminderEveryDays} BETWEEN 1 AND 31`),
  check('billing_payment_settings_one_owner_chk', sql`(${t.orgId} IS NULL) <> (${t.partnerId} IS NULL)`),
  check('billing_payment_settings_cap_chk', sql`(${t.autopayCapEnabled} IS TRUE AND ${t.autopayCapAmount} IS NOT NULL AND ${t.autopayCapCurrency} IS NOT NULL AND ${t.autopayCapAmount} > 0 AND ${t.autopayCapCurrency} ~ '^[A-Z]{3}$') OR (${t.autopayCapEnabled} IS NOT TRUE AND ${t.autopayCapAmount} IS NULL AND ${t.autopayCapCurrency} IS NULL)`),
  check('billing_payment_settings_attestation_chk', sql`(${t.feeAttestedBy} IS NULL) = (${t.feeAttestedAt} IS NULL) AND (${t.orgId} IS NULL OR ${t.feeAttestedAt} IS NULL)`),
  uniqueIndex('billing_payment_settings_partner_uq').on(t.partnerId).where(sql`${t.partnerId} IS NOT NULL`),
  uniqueIndex('billing_payment_settings_org_uq').on(t.orgId).where(sql`${t.orgId} IS NOT NULL`),
]);

export const orgAutopayEnrollments = pgTable('org_autopay_enrollments', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  partnerId: uuid('partner_id').notNull().references(() => partners.id),
  status: autopayEnrollmentStatusEnum('status').notNull().default('requested'),
  generation: integer('generation').notNull().default(1),
  stripeConnectionId: uuid('stripe_connection_id').notNull(),
  stripeAccountId: text('stripe_account_id').notNull(),
  stripeCustomerId: text('stripe_customer_id'),
  effectiveFrom: timestamp('effective_from', { withTimezone: true }),
  requestedBy: uuid('requested_by'),
  requestedAt: timestamp('requested_at', { withTimezone: true }),
  requestRecipientEmail: text('request_recipient_email'),
  pausedBy: uuid('paused_by'),
  pausedAt: timestamp('paused_at', { withTimezone: true }),
  cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
  cancelSource: text('cancel_source').$type<AutopayCancelSource>(),
  cancelReason: text('cancel_reason'),
  needsAttentionReason: text('needs_attention_reason').$type<AutopayNeedsAttentionReason>(),
}, (t) => [
  check('org_autopay_enrollments_cancelled_chk', sql`${t.status} <> 'cancelled' OR (${t.cancelledAt} IS NOT NULL AND ${t.cancelSource} IS NOT NULL)`),
  check('org_autopay_enrollments_active_chk', sql`${t.status} <> 'active' OR ${t.effectiveFrom} IS NOT NULL`),
  check('org_autopay_enrollments_generation_check', sql`${t.generation} > 0`),
  check('org_autopay_enrollments_cancel_source_check', sql`${t.cancelSource} IN ('client','msp','system')`),
  check('org_autopay_enrollments_needs_attention_reason_check', sql`${t.needsAttentionReason} IN ('method_unusable','stripe_account_changed','key_missing_permissions','verification_failed')`),
  unique().on(t.orgId),
  unique().on(t.id,t.orgId),
  foreignKey({name:'org_autopay_enrollments_org_partner_fk',columns:[t.orgId,t.partnerId],foreignColumns:[organizations.id,organizations.partnerId]}),
  foreignKey({name:'org_autopay_enrollments_connection_partner_fk',columns:[t.stripeConnectionId,t.partnerId],foreignColumns:[stripeConnectAccounts.id,stripeConnectAccounts.partnerId]}),
]);

export const orgPaymentMethods = pgTable('org_payment_methods', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  enrollmentId: uuid('enrollment_id').notNull(),
  stripePaymentMethodId: text('stripe_payment_method_id').notNull(),
  type: text('type').notNull().$type<AutopayPaymentMethodType>(),
  cardBrand: text('card_brand'),
  cardLast4: text('card_last4'),
  cardExpMonth: integer('card_exp_month'),
  cardExpYear: integer('card_exp_year'),
  cardFunding: text('card_funding').$type<CardFundingType>(),
  cardCountry: text('card_country'),
  bankName: text('bank_name'),
  bankLast4: text('bank_last4'),
  accountHolderType: text('account_holder_type').$type<AccountHolderType>(),
  stripeMandateId: text('stripe_mandate_id'),
  stripeSetupIntentId: text('stripe_setup_intent_id'),
  status: orgPaymentMethodStatusEnum('status').notNull().default('pending_verification'),
  unusableReason: text('unusable_reason'),
  isAutopayMethod: boolean('is_autopay_method').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  removedAt: timestamp('removed_at', { withTimezone: true }),
  detachFailedAt: timestamp('detach_failed_at', { withTimezone: true }),
  detachAttempts: integer('detach_attempts').notNull().default(0),
  detachNextAttemptAt: timestamp('detach_next_attempt_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  unique().on(t.orgId, t.stripePaymentMethodId),
  check('org_payment_methods_removed_chk', sql`${t.status} <> 'removed' OR ${t.removedAt} IS NOT NULL`),
  check('org_payment_methods_type_check', sql`${t.type} IN ('card','us_bank_account')`),
  check('org_payment_methods_card_exp_month_check', sql`${t.cardExpMonth} BETWEEN 1 AND 12`),
  check('org_payment_methods_card_funding_check', sql`${t.cardFunding} IN ('credit','debit','prepaid','unknown')`),
  check('org_payment_methods_account_holder_type_check', sql`${t.accountHolderType} IN ('individual','company')`),
  unique().on(t.id,t.orgId),
  foreignKey({name:'org_payment_methods_enrollment_org_fk',columns:[t.enrollmentId,t.orgId],foreignColumns:[orgAutopayEnrollments.id,orgAutopayEnrollments.orgId]}),
  uniqueIndex('org_payment_methods_autopay_uq').on(t.orgId).where(sql`${t.isAutopayMethod} AND ${t.status} IN ('active','pending_verification')`),
]);

export const orgAutopayConsents = pgTable('org_autopay_consents', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  enrollmentId: uuid('enrollment_id').notNull(),
  generation: integer('generation').notNull(),
  paymentMethodId: uuid('payment_method_id').notNull(),
  consentTextVersion: text('consent_text_version').notNull(),
  consentTextHash: text('consent_text_hash').notNull(),
  feeTerms: jsonb('fee_terms').notNull(),
  scheduleTerms: jsonb('schedule_terms').notNull(),
  contactEmail: text('contact_email').notNull(),
  ip: text('ip'),
  userAgent: text('user_agent'),
  source: text('source').notNull().$type<ConsentSource>(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  check('org_autopay_consents_generation_check', sql`${t.generation} > 0`),
  check('org_autopay_consents_source_check', sql`${t.source} IN ('setup_page','pay_and_save','portal')`),
  foreignKey({name:'org_autopay_consents_enrollment_org_fk',columns:[t.enrollmentId,t.orgId],foreignColumns:[orgAutopayEnrollments.id,orgAutopayEnrollments.orgId]}),
  foreignKey({name:'org_autopay_consents_method_org_fk',columns:[t.paymentMethodId,t.orgId],foreignColumns:[orgPaymentMethods.id,orgPaymentMethods.orgId]}),
]);

export const billingNoticeOutbox = pgTable('billing_notice_outbox', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  invoiceId: uuid('invoice_id'),
  enrollmentId: uuid('enrollment_id'),
  kind: billingNoticeKindEnum('kind').notNull(),
  seq: integer('seq').notNull(),
  dedupeKey: text('dedupe_key').notNull(),
  toEmail: text('to_email').notNull(),
  rendered: jsonb('rendered').notNull(),
  status: billingNoticeStatusEnum('status').notNull().default('pending'),
  attempts: integer('attempts').notNull().default(0),
  nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }).notNull().defaultNow(),
  sentAt: timestamp('sent_at', { withTimezone: true }),
  providerMessageId: text('provider_message_id'),
  lastError: text('last_error'),
}, (t) => [
  check('billing_notice_outbox_seq_check', sql`${t.seq} >= 0`),
  check('billing_notice_outbox_attempts_check', sql`${t.attempts} >= 0`),
  unique().on(t.dedupeKey),
  unique().on(t.id,t.orgId),
  foreignKey({name:'billing_notice_outbox_invoice_org_fk',columns:[t.invoiceId,t.orgId],foreignColumns:[invoices.id,invoices.orgId]}),
  foreignKey({name:'billing_notice_outbox_enrollment_org_fk',columns:[t.enrollmentId,t.orgId],foreignColumns:[orgAutopayEnrollments.id,orgAutopayEnrollments.orgId]}),
  index('billing_notice_outbox_dispatch_idx').on(t.status,t.nextAttemptAt),
]);

export const invoiceAutopaySchedules = pgTable('invoice_autopay_schedules', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  invoiceId: uuid('invoice_id').notNull(),
  enrollmentId: uuid('enrollment_id'),
  enrollmentGeneration: integer('enrollment_generation').notNull(),
  eligible: boolean('eligible').notNull(),
  ineligibleReason: text('ineligible_reason').$type<AutopayIneligibleReason>(),
  collectOn: date('collect_on'),
  termsSnapshot: jsonb('terms_snapshot').notNull(),
  noticeOutboxId: uuid('notice_outbox_id'),
  noticeSentAt: timestamp('notice_sent_at', { withTimezone: true }),
  state: autopayScheduleStateEnum('state').notNull().default('awaiting_notice'),
  stateReason: text('state_reason'),
  nextAttemptAt: timestamp('next_attempt_at', { withTimezone: true }),
  attemptCount: integer('attempt_count').notNull().default(0),
  clientSkippedAt: timestamp('client_skipped_at', { withTimezone: true }),
  mspExcludedBy: uuid('msp_excluded_by'),
  mspExcludedAt: timestamp('msp_excluded_at', { withTimezone: true }),
}, (t) => [
  check('invoice_autopay_schedules_eligible_chk', sql`${t.eligible} = (${t.ineligibleReason} IS NULL)`),
  check('invoice_autopay_schedules_collect_on_chk', sql`${t.state} NOT IN ('scheduled','retry_scheduled') OR ${t.collectOn} IS NOT NULL`),
  check('invoice_autopay_schedules_ineligible_reason_check', sql`${t.ineligibleReason} IN ('not_enrolled','enrolled_after_issue','method_not_usable','over_cap','cap_currency_mismatch','ach_currency_unsupported','excluded_contract','excluded_invoice','charging_disabled','stripe_unavailable')`),
  check('invoice_autopay_schedules_attempt_count_check', sql`${t.attemptCount} >= 0`),
  check('invoice_autopay_schedules_authority_chk', sql`${t.enrollmentId} IS NOT NULL OR ${t.state} IN ('succeeded','failed','skipped_by_client','excluded_by_msp','cancelled','not_needed')`),
  unique().on(t.invoiceId),
  unique().on(t.id,t.orgId),
  foreignKey({name:'invoice_autopay_schedules_invoice_org_fk',columns:[t.invoiceId,t.orgId],foreignColumns:[invoices.id,invoices.orgId]}),
  foreignKey({name:'invoice_autopay_schedules_enrollment_org_fk',columns:[t.enrollmentId,t.orgId],foreignColumns:[orgAutopayEnrollments.id,orgAutopayEnrollments.orgId]}),
  foreignKey({name:'invoice_autopay_schedules_notice_org_fk',columns:[t.noticeOutboxId,t.orgId],foreignColumns:[billingNoticeOutbox.id,billingNoticeOutbox.orgId]}),
  index('invoice_autopay_schedules_due_idx').on(t.state,t.collectOn,t.nextAttemptAt),
]);

export const invoiceCollectionAttempts = pgTable('invoice_collection_attempts', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  invoiceId: uuid('invoice_id').notNull(),
  scheduleId: uuid('schedule_id'),
  attemptNo: integer('attempt_no').notNull(),
  paymentMethodId: uuid('payment_method_id'),
  stripePaymentIntentId: text('stripe_payment_intent_id'),
  idempotencyKey: text('idempotency_key').notNull(),
  principalAmount: numeric('principal_amount', { precision: 12, scale: 2 }).notNull(),
  feeAmount: numeric('fee_amount', { precision: 12, scale: 2 }).notNull().default('0'),
  currency: char('currency', { length: 3 }).notNull(),
  state: collectionAttemptStateEnum('state').notNull().default('reserved'),
  failureCode: text('failure_code'),
  declineCode: text('decline_code'),
  failureClass: text('failure_class').$type<CollectionFailureClass>(),
  invoiceStripePaymentId: uuid('invoice_stripe_payment_id'),
  initiatedBy: text('initiated_by').notNull().$type<CollectionAttemptInitiator>(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  check('invoice_collection_attempts_currency_chk', sql`${t.currency} ~ '^[A-Z]{3}$'`),
  check('invoice_collection_attempts_attempt_no_check', sql`${t.attemptNo} > 0`),
  check('invoice_collection_attempts_principal_amount_check', sql`${t.principalAmount} > 0`),
  check('invoice_collection_attempts_fee_amount_check', sql`${t.feeAmount} >= 0`),
  check('invoice_collection_attempts_failure_class_check', sql`${t.failureClass} IN ('soft','hard','auth_required','nsf','revoked')`),
  check('invoice_collection_attempts_initiated_by_check', sql`${t.initiatedBy} IN ('scheduler','msp_charge_now','client_on_session')`),
  check('invoice_collection_attempts_schedule_chk', sql`${t.scheduleId} IS NOT NULL OR ${t.initiatedBy}='client_on_session'`),
  check('invoice_collection_attempts_authority_chk', sql`${t.paymentMethodId} IS NOT NULL OR ${t.state} IN ('succeeded','failed','canceled','unapplied')`),
  unique().on(t.idempotencyKey),
  unique().on(t.stripePaymentIntentId),
  unique().on(t.scheduleId,t.attemptNo),
  foreignKey({name:'invoice_collection_attempts_invoice_org_fk',columns:[t.invoiceId,t.orgId],foreignColumns:[invoices.id,invoices.orgId]}),
  foreignKey({name:'invoice_collection_attempts_schedule_org_fk',columns:[t.scheduleId,t.orgId],foreignColumns:[invoiceAutopaySchedules.id,invoiceAutopaySchedules.orgId]}),
  foreignKey({name:'invoice_collection_attempts_method_org_fk',columns:[t.paymentMethodId,t.orgId],foreignColumns:[orgPaymentMethods.id,orgPaymentMethods.orgId]}),
  foreignKey({name:'invoice_collection_attempts_mapping_org_fk',columns:[t.invoiceStripePaymentId,t.orgId],foreignColumns:[invoiceStripePayments.id,invoiceStripePayments.orgId]}),
  index('invoice_collection_attempts_active_idx').on(t.invoiceId,t.state).where(sql`${t.state} IN ('reserved','created','confirming','processing','requires_action')`),
]);

export const billingLinkTokens = pgTable('billing_link_tokens', {
  id: uuid('id').primaryKey().defaultRandom(),
  orgId: uuid('org_id').notNull().references(() => organizations.id),
  purpose: billingLinkPurposeEnum('purpose').notNull(),
  tokenHash: text('token_hash').notNull(),
  tokenCt: text('token_ct').notNull(),
  enrollmentId: uuid('enrollment_id'),
  invoiceId: uuid('invoice_id'),
  generation: integer('generation'),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  consumedAt: timestamp('consumed_at', { withTimezone: true }),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
}, (t) => [
  check('billing_link_tokens_invoice_chk', sql`${t.purpose} NOT IN ('skip_invoice','confirm_payment') OR ${t.invoiceId} IS NOT NULL`),
  check('billing_link_tokens_enrollment_chk', sql`${t.purpose} NOT IN ('enroll','stop_autopay') OR ${t.enrollmentId} IS NOT NULL`),
  check('billing_link_tokens_generation_check', sql`${t.generation} > 0`),
  unique().on(t.tokenHash),
  foreignKey({name:'billing_link_tokens_invoice_org_fk',columns:[t.invoiceId,t.orgId],foreignColumns:[invoices.id,invoices.orgId]}),
  foreignKey({name:'billing_link_tokens_enrollment_org_fk',columns:[t.enrollmentId,t.orgId],foreignColumns:[orgAutopayEnrollments.id,orgAutopayEnrollments.orgId]}),
]);
