import '../../__tests__/integration/setup';
import { randomUUID } from 'node:crypto';
import { expect,it } from 'vitest';
import { eq } from 'drizzle-orm';
import { withDbAccessContext } from '../../db';
import { devices,deviceHardwareHealth,deviceHardwareComponents,deviceHardwareEvents } from '../../db/schema';
import { getTestDb } from '../../__tests__/integration/setup';
import { createPartner,createOrganization,createSite } from '../../__tests__/integration/db-utils';
import { hardwareHealthSnapshotSchema } from '@breeze/shared';
import { ingestHardwareHealthSnapshot } from './ingest';
it('serializes two same-sequence restart snapshots and rejects without writes',async()=>{
 const partner=await createPartner(),org=await createOrganization({partnerId:partner!.id}),site=await createSite({orgId:org!.id});
 const [device]=await getTestDb().insert(devices).values({orgId:org!.id,siteId:site!.id,agentId:randomUUID(),hostname:'raid',osType:'linux',osVersion:'1',architecture:'x64',agentVersion:'1.0.0'}).returning();
 const ctx={scope:'organization' as const,orgId:org!.id,accessibleOrgIds:[org!.id],currentPartnerId:partner!.id};
 const first=new Date('2026-09-23T12:00:00Z');
 const snapshot=hardwareHealthSnapshotSchema.parse({snapshotId:randomUUID(),sequence:50,collectedAt:'2099-01-01T00:00:00Z',agentVersion:'1',pollIntervalMinutes:10,diskHealthIntervalMinutes:60,tiersRun:['raid'],sources:[{source:'storcli',status:'ok',complete:true}],components:[{componentKey:'storcli:c0',componentType:'controller',source:'storcli',name:'Controller',state:'failed'}]});
 const send=(sequence:number,receivedAt:Date,writer:'agent'|'server'='agent')=>withDbAccessContext(ctx,()=>ingestHardwareHealthSnapshot({device:device!,snapshot:{...snapshot,snapshotId:randomUUID(),sequence},writer,receivedAt}));
 await send(50,first);
 expect(await send(0,new Date(+first+3_600_000))).toEqual({accepted:false,reason:'stale_snapshot'});
 const race=await Promise.all([send(0,new Date(+first+3_600_001)),send(0,new Date(+first+3_600_001))]);
 expect(race.filter(r=>r.accepted)).toHaveLength(1);
 const [health]=await getTestDb().select().from(deviceHardwareHealth).where(eq(deviceHardwareHealth.deviceId,device!.id));
 expect(health).toMatchObject({lastAgentSequence:0,lastReceivedAt:new Date(+first+3_600_001)});
 const rows=await getTestDb().select().from(deviceHardwareComponents).where(eq(deviceHardwareComponents.deviceId,device!.id));
 expect(rows.find(r=>r.componentKey==='storcli:c0')!.criticalStreak).toBe(2);
 expect(await getTestDb().select().from(deviceHardwareEvents).where(eq(deviceHardwareEvents.deviceId,device!.id))).toHaveLength(2);
 await send(999,new Date(+first+7_200_000),'server');
 const [after]=await getTestDb().select().from(deviceHardwareHealth).where(eq(deviceHardwareHealth.deviceId,device!.id));
 expect(after!.lastAgentSequence).toBe(0);expect(after!.lastReceivedAt).toEqual(health!.lastReceivedAt);
 await expect(withDbAccessContext(ctx,()=>ingestHardwareHealthSnapshot({device:device!,snapshot:{...snapshot,sequence:1,components:[{...snapshot.components[0]!,state:'illegal'}]},writer:'agent',receivedAt:new Date(+first+7_200_001)}))).rejects.toThrow('components.0.state');
 const [unchanged]=await getTestDb().select().from(deviceHardwareHealth).where(eq(deviceHardwareHealth.deviceId,device!.id));
 expect(unchanged!.lastAgentSequence).toBe(0);
});
