#!/usr/bin/env bash

# Behavioral guard: the systemd unit that guided-setup.sh installs must be a
# valid unit file.
#
# Why this guard exists
# ---------------------
# The unit is generated from a heredoc, so nothing validates it until a
# self-hoster's `systemctl enable --now` fails at install time. That happened
# with `Type=oneshot` + `Restart=on-failure` (#4201): systemd rejects that
# combination outright ("bad unit file setting"), so the reboot-startup service
# the installer offered never started, and the failure surfaced on the
# customer's box, not in CI. oneshot units may only use Restart=no or
# Restart=on-abnormal-style values via RemainAfterExit semantics — in practice
# the service relies on docker.service ordering, so no Restart= at all is
# correct here.
#
# The check extracts the unit heredoc generated by guided-setup.sh and asserts
# the oneshot/Restart combination cannot come back. It deliberately does NOT run
# systemd-analyze: the heredoc is a template with unexpanded $(shell_quote ...)
# substitutions, which a full verifier rejects for reasons unrelated to what
# this guards.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SETUP="${REPO_ROOT}/scripts/guided-setup.sh"

fail=0

# Pull the generated unit text (heredoc bodies containing a [Service] header).
unit_text="$(awk '/^\[Unit\]$/,/^EOF$/' "${SETUP}")"

if [[ -z "${unit_text}" ]]; then
  echo "ERROR: could not locate the generated systemd unit heredoc in ${SETUP}" >&2
  exit 1
fi

if grep -q '^Type=oneshot' <<<"${unit_text}" && grep -Eq '^Restart=(always|on-failure|on-success|on-abort|on-watchdog)' <<<"${unit_text}"; then
  echo "ERROR: generated unit combines Type=oneshot with a Restart= value systemd rejects (\"bad unit file setting\", #4201)." >&2
  fail=1
fi

if [[ "${fail}" -ne 0 ]]; then
  exit 1
fi
echo "guided-setup systemd unit: OK"
