#!/usr/bin/env tsx
/**
 * Schema Drift Check
 *
 * Runs `drizzle-kit generate` and checks if any new migration files are
 * produced. If so, the Drizzle schema has changed without a corresponding
 * migration being committed.
 *
 * This is authoritative because drizzle-kit uses the same diffing logic
 * it uses to create migrations — if it produces output, there's drift.
 *
 * Usage:
 *   pnpm check:schema-drift
 *   # or directly:
 *   tsx scripts/check-schema-drift.ts
 *
 * Exit code 0 = no drift, 1 = uncommitted schema changes detected.
 */

import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
const API_DIR = path.join(REPO_ROOT, 'apps/api');

const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const NC = '\x1b[0m';

function main() {
  // Run drizzle-kit generate to see if any new migration files would be created
  console.log('Running drizzle-kit generate to check for schema drift...\n');

  try {
    execSync('pnpm drizzle-kit generate', {
      cwd: API_DIR,
      stdio: 'pipe',
    });
    // Fix invalid PG syntax (CREATE TYPE IF NOT EXISTS) generated by drizzle-kit
    execSync('bash scripts/fix-drizzle-enums.sh', {
      cwd: API_DIR,
      stdio: 'pipe',
    });
  } catch (err: any) {
    console.error(`${RED}drizzle-kit generate failed:${NC}`);
    console.error(err.stderr?.toString() || err.message);
    process.exit(1);
  }

  // Check if any new migration files were produced
  let diff = '';
  try {
    diff = execSync('git diff --name-only apps/api/drizzle/', {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }).trim();
  } catch {
    // git diff returns non-zero if there are issues
  }

  // Also check for untracked files in drizzle/
  let untracked = '';
  try {
    untracked = execSync('git ls-files --others --exclude-standard apps/api/drizzle/', {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    }).trim();
  } catch {
    // ignore
  }

  const changedFiles = [diff, untracked].filter(Boolean).join('\n');

  if (changedFiles) {
    console.log(`${RED}SCHEMA DRIFT DETECTED${NC}\n`);
    console.log('The following migration files were generated by drizzle-kit:\n');
    for (const file of changedFiles.split('\n')) {
      console.log(`  ${RED}+${NC} ${file}`);
    }
    console.log(
      `\n${YELLOW}Fix: Run 'cd apps/api && pnpm db:generate' and commit the new migration file.${NC}`,
    );
    // Clean up generated files so we don't leave dirty state
    try {
      execSync('git checkout -- apps/api/drizzle/', { cwd: REPO_ROOT, stdio: 'pipe' });
    } catch {
      // ignore cleanup failures
    }
    if (untracked) {
      for (const file of untracked.split('\n')) {
        try {
          execSync(`rm -f "${REPO_ROOT}/${file}"`, { cwd: REPO_ROOT, stdio: 'pipe' });
        } catch {
          // ignore cleanup failures
        }
      }
    }
    process.exit(1);
  }

  console.log(`${GREEN}✓ No schema drift detected. All schema changes have corresponding migrations.${NC}`);
}

main();
