import { beforeEach,expect,it,vi } from 'vitest';
import { Hono } from 'hono';
const m=vi.hoisted(()=>({ingest:vi.fn(),authIds:[] as string[]}));
vi.mock('../../db',()=>({db:{select:()=>({from:()=>({where:()=>({limit:async()=>[{id:'11111111-1111-4111-8111-111111111111',orgId:'22222222-2222-4222-8222-222222222222'}]})})})}}));
vi.mock('../../services/hardwareHealth/ingest',()=>({ingestHardwareHealthSnapshot:m.ingest,InvalidHardwareSnapshotError:class extends Error{constructor(public path:string){super(path);}}}));
vi.mock('../../middleware/agentAuth',()=>({agentAuthMiddleware:async(c:any,next:any)=>{m.authIds.push(c.req.param('id'));c.set('agent',{role:'agent'});return next();}}));
vi.mock('./download',async()=>({downloadRoutes:new (await import('hono')).Hono()}));
vi.mock('./enrollment',async()=>({enrollmentRoutes:new (await import('hono')).Hono()}));
vi.mock('./heartbeat',async()=>({heartbeatRoutes:new (await import('hono')).Hono()}));
vi.mock('./uninstallIntent',async()=>({uninstallIntentRoutes:new (await import('hono')).Hono()}));
vi.mock('./commands',async()=>({commandsRoutes:new (await import('hono')).Hono()}));
vi.mock('./pamObservations',async()=>({pamObservationRoutes:new (await import('hono')).Hono()}));
vi.mock('./pamReconciliation',async()=>({pamReconciliationRoutes:new (await import('hono')).Hono()}));
vi.mock('./security',async()=>({agentSecurityRoutes:new (await import('hono')).Hono()}));
vi.mock('./recoveryKeys',async()=>({agentRecoveryKeysRoutes:new (await import('hono')).Hono()}));
vi.mock('./inventory',async()=>({inventoryRoutes:new (await import('hono')).Hono()}));
vi.mock('./state',async()=>({stateRoutes:new (await import('hono')).Hono()}));
vi.mock('./sessions',async()=>({sessionsRoutes:new (await import('hono')).Hono()}));
vi.mock('./patches',async()=>({patchesRoutes:new (await import('hono')).Hono()}));
vi.mock('./connections',async()=>({connectionsRoutes:new (await import('hono')).Hono()}));
vi.mock('./eventlogs',async()=>({eventLogsRoutes:new (await import('hono')).Hono()}));
vi.mock('./logs',async()=>({logsRoutes:new (await import('hono')).Hono()}));
vi.mock('./mtls',async()=>({mtlsRoutes:new (await import('hono')).Hono()}));
vi.mock('./bootPerformance',async()=>({bootPerformanceRoutes:new (await import('hono')).Hono()}));
vi.mock('./reliability',async()=>({reliabilityRoutes:new (await import('hono')).Hono()}));
vi.mock('./changes',async()=>({changesRoutes:new (await import('hono')).Hono()}));
vi.mock('./peripherals',async()=>({peripheralRoutes:new (await import('hono')).Hono()}));
vi.mock('./token',async()=>({tokenRoutes:new (await import('hono')).Hono()}));
vi.mock('./elevationRequests',async()=>({elevationRequestsRoutes:new (await import('hono')).Hono()}));
vi.mock('./processSample',async()=>({processSampleRoutes:new (await import('hono')).Hono()}));
vi.mock('./unifiTelemetry',async()=>({unifiTelemetryRoutes:new (await import('hono')).Hono()}));
vi.mock('./wingetBootstrap',async()=>({wingetBootstrapRoutes:new (await import('hono')).Hono()}));
import { agentRoutes } from './index';
import { hardwareHealthSnapshotSchema } from '@breeze/shared';
import { createGlobalBodyLimitMiddleware } from '../../middleware/bodyLimitGate';
const wire={snapshotId:'33333333-3333-4333-8333-333333333333',sequence:1,collectedAt:'2026-09-23T00:00:00Z',agentVersion:'1',pollIntervalMinutes:10,diskHealthIntervalMinutes:60,tiersRun:['disk'],sources:[{source:'smartctl',status:'ok',complete:true}],components:Array.from({length:220},(_,i)=>({componentKey:`smart:serial-${i}`,componentType:'physical_disk',source:'smartctl',name:`Disk ${i}`,state:'online',attributes:{padding:'x'.repeat(7000)}}))};
const json=JSON.stringify(wire);
const app=new Hono();
app.use('*',createGlobalBodyLimitMiddleware({warn:()=>{},capture:()=>{}}));
app.route('/api/v1/agents',agentRoutes);
beforeEach(()=>{m.authIds=[];m.ingest.mockReset().mockResolvedValue({accepted:true,events:220,health:'ok'});});
function request(body:string,withLength:boolean){
 const headers:Record<string,string>={'content-type':'application/json'};
 if(withLength)headers['content-length']=String(Buffer.byteLength(body));
 return app.request('/api/v1/agents/agent-1/hardware-health',{method:'PUT',headers,body});
}
it.each([false,true])('accepts a valid snapshot between 1 and 2 MiB (Content-Length: %s)',async withLength=>{
 expect(Buffer.byteLength(json)).toBeGreaterThan(1024*1024);expect(Buffer.byteLength(json)).toBeLessThan(2*1024*1024);
 expect(hardwareHealthSnapshotSchema.safeParse(wire).success).toBe(true);
 const res=await request(json,withLength);expect(res.status).toBe(200);expect(await res.json()).toEqual({accepted:true,events:220});
 expect(m.authIds).toEqual(['agent-1']);expect(m.ingest).toHaveBeenCalledOnce();
});
it.each([false,true])('accepts the byte boundary and rejects one byte over (Content-Length: %s)',async withLength=>{
 const exact=json+' '.repeat(2*1024*1024-Buffer.byteLength(json));
 expect((await request(exact,withLength)).status).toBe(200);
 m.ingest.mockClear();m.authIds=[];
 expect((await request(exact+' ',withLength)).status).toBe(413);
 expect(m.ingest).not.toHaveBeenCalled();expect(m.authIds).toEqual([]);
});
